version: "3"
services:
  docker-tutorial:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    env_file: 
      - ./.env
    command: node index.js